export const MAPPING = {
  A_A:'Alert,All',
  A_A_CLAIM:'Alert,All,Claim',
  A_A_CLOSE:'Alert,All,Close',
  A_A_CLOSURE_NOTE:'Alert,All,Closure Note',
  A_A_UPLOAD_EVDIENCE:'Alert,All,Upload Evidence',
  A_A_CREATE_CASE:'Alert,All,CreateCase',
  A_A_ADD_NOTE:'Alert,All,AddNote',
  A_A_MORE_FILTERS:'Alert,All,More Filters',
  A_I_P:'Alert,In-process',
  A_I_P_CLAIM:'Alert,In-process,Claim',
  A_I_P_CLOSE:'Alert,In-process,Close',
  A_I_P_CLOSURE_NOTE:'Alert,In-process,Closure Note',
  A_I_P_UPLOAD_EVDIENCE:'Alert,In-process,Upload Evidence',
  A_I_P_CREATE_CASE:'Alert,In-process,CreateCase',
  A_I_P_ADD_NOTE:'Alert,In-process,AddNote',
  A_I_P_MORE_FILTERS:'Alert,In-process,More Filters',
  A_C:'Alert,Close',
  A_C_CLAIM:'Alert,Close,Claim',
  A_C_CLOSE:'Alert,Close,Close',
  A_C_CLOSURE_NOTE:'Alert,Close,Closure Note',
  A_C_UPLOAD_EVDIENCE:'Alert,Close,Upload Evidence',
  A_C_CREATE_CASE:'Alert,Close,CreateCase',
  A_C_ADD_NOTE:'Alert,Close,AddNote',
  A_C_MORE_FILTERS:'Alert,Close,More Filters',
  A_M:'Alert,My Alerts',
  A_M_CLAIM:'Alert,My Alerts,Claim',
  A_M_CLOSE:'Alert,My Alerts,Close',
  A_M_CLOSURE_NOTE:'Alert,My Alerts,Closure Note',
  A_M_UPLOAD_EVDIENCE:'Alert,My Alerts,Upload Evidence',
  A_M_CREATE_CASE:'Alert,My Alerts,CreateCase',
  A_M_ADD_NOTE:'Alert,My Alerts,AddNote',
  A_M_MORE_FILTERS:'Alert,My Alerts,More Filters',
  A_U:'Alert,Unclaimed',
  A_U_CLAIM:'Alert,Unclaimed,Claim',
  A_U_CLOSE:'Alert,Unclaimed,Close',
  A_U_CLOSURE_NOTE:'Alert,Unclaimed,Closure Note',
  A_U_UPLOAD_EVDIENCE:'Alert,Unclaimed,Upload Evidence',
  A_U_CREATE_CASE:'Alert,Unclaimed,CreateCase',
  A_U_ADD_NOTE:'Alert,Unclaimed,AddNote',
  A_U_MORE_FILTERS:'Alert,Unclaimed,More Filters',
  C_A:'Case,All',
  C_A_CLAIM:'Case,All,Claim',
  C_A_CLOSE:'Case,All,Close',
  C_A_CLOSURE_NOTE:'Case,All,Closure Note',
  C_A_UPLOAD_EVDIENCE:'Case,All,Upload Evidence',
  C_A_CREATE_CASE:'Case,All,CreateCase',
  C_A_ADD_NOTE:'Case,All,AddNote',
  C_A_MORE_FILTERS:'Case,All,More Filters',
  C_I_P:'Case,In-process',
  C_I_P_CLAIM:'Case,In-process,Claim',
  C_I_P_CLOSE:'Case,In-process,Close',
  C_I_P_CLOSURE_NOTE:'Case,In-process,Closure Note',
  C_I_P_UPLOAD_EVDIENCE:'Case,In-process,Upload Evidence',
  C_I_P_CREATE_CASE:'Case,In-process,CreateCase',
  C_I_P_ADD_NOTE:'Case,In-process,AddNote',
  C_I_P_MORE_FILTERS:'Case,In-process,More Filters',
  C_C:'Case,Close',
  C_C_CLAIM:'Case,Close,Claim',
  C_C_CLOSE:'Case,Close,Close',
  C_C_CLOSURE_NOTE:'Case,Close,Closure Note',
  C_C_UPLOAD_EVDIENCE:'Case,Close,Upload Evidence',
  C_C_CREATE_CASE:'Case,Close,CreateCase',
  C_C_ADD_NOTE:'Case,Close,AddNote',
  C_C_MORE_FILTERS:'Case,Close,More Filters',
  C_M:'Case,My Alerts',
  C_M_CLAIM:'Case,My Alerts,Claim',
  C_M_CLOSE:'Case,My Alerts,Close',
  C_M_CLOSURE_NOTE:'Case,My Alerts,Closure Note',
  C_M_UPLOAD_EVDIENCE:'Case,My Alerts,Upload Evidence',
  C_M_CREATE_CASE:'Case,My Alerts,CreateCase',
  C_M_ADD_NOTE:'Case,My Alerts,AddNote',
  C_M_MORE_FILTERS:'Case,My Alerts,More Filters',
  C_O:'Case,Open',
  C_O_CLAIM:'Case,Open,Claim',
  C_O_CLOSE:'Case,Open,Close',
  C_O_CLOSURE_NOTE:'Case,Open,Closure Note',
  C_O_UPLOAD_EVDIENCE:'Case,Open,Upload Evidence',
  C_O_CREATE_CASE:'Case,Open,CreateCase',
  C_O_ADD_NOTE:'Case,Open,AddNote',
  C_O_MORE_FILTERS:'Case,Open,More Filters',
  CONF_A_M_A:'Configuration,Asset ManagementAsset',
  CONF_A_M_A_C:'Configuration,Asset ManagementAsset,Create',
  CONF_A_M_A_E:'Configuration,Asset ManagementAsset,Edit',
  CONF_A_M_B:'Configuration,Asset ManagementBlock',
  CONF_A_M_B_C:'Configuration,Asset ManagementBlock,Create',
  CONF_A_M_B_E:'Configuration,Asset ManagementBlock,Edit',
  CONF_A_M_G:'Configuration,Asset ManagementGroup',
  CONF_A_M_G_C:'Configuration,Asset ManagementGroup,Create',
  CONF_A_M_G_E:'Configuration,Asset ManagementGroup,Edit',
  CONF_A_M_P:'Configuration,Asset ManagementPlant',
  CONF_A_M_P_C:'Configuration,Asset ManagementPlant,Create',
  CONF_A_M_P_E:'Configuration,Asset ManagementPlant,Edit',
  CONF_A_M_S:'Configuration,Asset ManagementSite',
  CONF_A_M_S_C:'Configuration,Asset ManagementSite,Create',
  CONF_A_M_S_E:'Configuration,Asset ManagementSite,Edit',
  CONF_A_M_T:'Configuration,Asset ManagementTag',
  CONF_A_M_T_C:'Configuration,Asset ManagementTag,Create',
  CONF_A_M_T_E:'Configuration,Asset ManagementTag,Edit',
  CONF_A_M_U:'Configuration,Asset ManagementUnit',
  CONF_IE_M:'Configuration,Import/Export Management',
  CONF_IE_M_I:'Configuration,Import/Export Management,Import',
  CONF_IE_M_E:'Configuration,Import/Export Management,Export',
  CONF_K_M:'Configuration,KPI Management',
  CONF_K_M_E:'Configuration,KPI Management,Edit',
  CONF_M_M:'Configuration,Message Management',
  CONF_M_M_E:'Configuration,Message Management,Edit',
  CONF_P_M:'Configuration,Permission Management',
  CONF_P_M_S:'Configuration,Permission Management,Save',
  CONF_R_M:'Configuration,Role Management',
  CONF_R_M_C:'Configuration,Role Management,Create',
  CONF_R_M_E:'Configuration,Role Management,Edit',
  CONF_U_M:'Configuration,User Management',
  CONF_U_M_C:'Configuration,User Management,Create',
  CONF_U_M_E:'Configuration,User Management,Edit',
  KNL_KNL:'Knowledge Search,Knowledge Search',
  KNL_KNL_F:'Knowledge Search,Knowledge Search,Filter',
  MAPPING_DIVIDER: ','
};
